update installForVPS

diff --git a/installForVPS b/installForVPS
--- a/installForVPS
+++ b/installForVPS
@@ -2,21 +2,31 @@
 SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 cd "$SCRIPTDIR"
 
+if (($EUID!=0));then
+    #非root用户的时候,需要检测是否有sudo命令,如果有还要检测当前用户可以使用sudo命令
+    #因为下面有的指令需要root权限
+    if command -v sudo >/dev/null 2>&1;then
+        sudo true || { echo "Error: Current user cannot use command 'sudo' !";exit 1; }
+    else
+        echo "Error: Current user is not root,and can not find sudo cmd!"
+        exit 1
+    fi
+fi
 case $(uname) in
     Darwin)
         OS="Darwin"
         ;;
     Linux)
         if command -v pacman >/dev/null 2>&1;then
-            OS="Arch"
+            OS="arch"
         elif command -v dnf >/dev/null 2>&1;then
-            OS="Fedora"
+            OS="fedora"
         elif command -v apt-get >/dev/null 2>&1;then
             if lsb_release -a 2>/dev/null |grep Debian >/dev/null 2>&1;then
-                OS="Debian"
+                OS="debian"
             fi
             if lsb_release -a 2>/dev/null |grep Ubuntu >/dev/null 2>&1;then
-                OS="Ubuntu"
+                OS="ubuntu"
             fi
         fi
         ;;
@@ -24,90 +34,56 @@ case $(uname) in
         echo "Not support your OS!"
         exit 1
 esac
-echo "OS: $OS"
 
-installDev=y
+user=${SUDO_USER:-$(whoami)}
+#installDev=y
+setSupervim=y
 setGit=y
 setShell=y
-setSupervim=y
 
 setDocker=n
-setProxy=n
 setGolang=n
 # read -p "Install dev tools? [Y/n] " installDev
-# read -p "Set proxy?(ie http_proxy https_proxy)[Y/n] " setProxy
 # read -p "Set git? [Y/n] " setGit
-# read -p "Set docker? [y/N] (only support arch)" setDocker
-# read -p "Set golang? [y/N] " setGolang
+#read -p "Set docker? [y/N] (only support arch)" setDocker
+#read -p "Set golang? [y/N] " setGolang
 # read -p "Set shell? [Y/n] (install zsh,zsh theme,source .custom-shell) " setShell
 # read -p "Set supervim? [Y/n] " setSupervim
 ##Install dev tools
-if [[ "$installDev" != [nN] ]];then
-    echo "Install dev tools..."
-    cd dev
-    case "$OS" in
-        "Arch")
-            sudo /bin/bash dev-arch
-            ;;
-        "Fedora")
-            sudo /bin/bash dev-fedora
-            ;;
-        "Ubuntu")
-            sudo /bin/bash dev-ubuntu
-            ;;
-        "Debian")
-            /bin/bash dev-debian
-            read -p "set iptables? [Y/n] " setIp
-            if [[ "$setIp" != [nN] ]];then
-                cd service/iptablesService && bash install.sh && cd -
-            fi
-            ;;
-        "Darwin")
-            /bin/bash dev-mac
-            ;;
-    esac
-    cd -
-    echo "Done."
+if (($EUID!=0));then
+    echo "You are not running the script by root privilege"
+    echo "Try to use sudo..."
+    sudo /bin/bash dev/dev-$OS
+else
+    /bin/bash dev/dev-$OS
 fi
 
-##Set proxy
-if [[ "$setProxy" != [nN] ]];then
-    # echo "Set proxy..."
-    # if [ ! -e /usr/local/bin/ss-client ];then
-    #     echo "Error: Can't find ss-client!"
-    #     exit 1
-    # fi
-    # sudo /usr/local/bin/ss-client globalRestart
-    ssclient-go globalRestart
-    if netstat -tan |grep -q 8118;then
-        export http_proxy=localhost:8118
-        export HTTP_PROXY=localhost:8118
-        export https_proxy=localhost:8118
-        export HTTPS_PROXY=localhost:8118
+if (($?!=0));then
+    echo "Run dev-$OS failed!"
+    exit 1
+fi
+read -p "set iptables service (for systemd)? [Y/n] " setIp
+if [[ "$setIp" != [nN] ]];then
+    if (($EUID!=0));then
+        sudo /bin/bash service/iptablesService/install.sh
     else
-        echo "Warning:http(s) proxy set error: can not find listen port on 8118"
+        /bin/bash service/iptablesService/install.sh
     fi
 fi
+
 ##Set git
 if [[ "$setGit" != [nN] ]];then
-    echo "Set git..."
-    cd git
-    /bin/bash setGit
-    cd -
-    echo "Done."
+    echo "Config git..."
+    /bin/bash git/setGit
 fi
 
 ##Set docker
 if [[ "$setDocker" == [yY] ]];then
-    echo "Set docker..."
-    cd docker
     case "$OS" in
         "Arch")
-            /bin/bash docker-arch install
+            /bin/bash docker/docker-arch install
             ;;
     esac
-    cd -
-    echo "Done."
 fi
 
 ##Set golang
@@ -125,27 +101,26 @@ fi
 ##Set shell
 if [[ "$setShell" != [nN] ]];then
     echo "Install zsh and oh-my-zsh..."
-    cd shell
-    /bin/bash 10-zsh-installer.sh
-    /bin/bash 20-set-zsh-theme.sh
-    /bin/bash 30-config-shell.sh install
-    cd -
+    /bin/bash shell/10-zsh-installer.sh
+    /bin/bash shell/20-set-zsh-theme.sh
+    /bin/bash shell/30-config-shell.sh install
     echo "Done."
 fi
 
-
 ##Set vim
 if [[ "$setSupervim" != [nN] ]];then
-    echo "Install supervim without vim-go and YouCompleteMe..."
+    echo "Install supervim with vim-go and YouCompleteMe..."
     cd supervim
     case "$OS" in
         Arch|Darwin)
-            /bin/bash install nvim
+            /bin/bash install -pgy nvim
             ;;
         *)
-            /bin/bash install vim
+            /bin/bash install -pgy vim
             ;;
     esac
     cd -
     echo "Done."
 fi
+
+# vim: set filetype=sh
