su $USER to install apps

diff --git a/dev/dev-mac b/dev/dev-mac
--- a/dev/dev-mac
+++ b/dev/dev-mac
@@ -12,6 +12,7 @@ function usage(){
     exit 0
 }
 
+USER=${SUDO_USER:-$(whoami)}
 proxy=
 while getopts ":hlp:" opt;do
     case "$opt" in
@@ -60,7 +61,8 @@ fi
 #install homebrew
 if ! command -v brew >/dev/null;then
     echo "install homebrew..."
-    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" || { echo "Install homebrew failed!"; exit 1; }
+    su $USER -c "curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install|/usr/bin/ruby"
+    #/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" || { echo "Install homebrew failed!"; exit 1; }
 fi
 
 #apps="coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt gnu-which wget go neovim vim python python3 privoxy aria2"
@@ -68,7 +70,7 @@ apps="coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt gnu-
 for app in $apps;do
     if ! brew list $app >/dev/null 2>&1;then
         echo "Install $app..."
-        brew install $app
+        su $USER -c "brew install $app"
     fi
 done
 #BREW install coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt gnu-which wget go neovim vim python python3 privoxy aria2
@@ -76,5 +78,4 @@ SBIN=$(find /usr/local/Cellar/privoxy -name "sbin")
 ln -svf  $SBIN/privoxy /usr/local/bin/privoxy
 pkill privoxy
 #brew tap homebrew/dupes;
-brew install grep
-
+su $USER -c "brew install grep"
