统一使用enable来增加端口,不存在则增加,存在则更新enable为1

diff --git a/service/iptablesService/stop-iptables b/service/iptablesService/stop-iptables
--- a/service/iptablesService/stop-iptables
+++ b/service/iptablesService/stop-iptables
@@ -9,7 +9,7 @@ iptables -nvxLINPUT|grep -v Chain|grep -v pkts| while read record;do
     echo "new traffic:$traffic"
     echo "type:$type"
     echo "port:$port"
-    sqlite3 "$db" "update portConfig set inputTraffic = inputTraffic + $traffic where type=\"$type\" and port=$port;" || { echo "update $type:$port input traffic failed!" ;}
+    sqlite3 "$db" "update portConfig set inputTraffic = inputTraffic + $traffic where type=\"$type\" and port=$port;" || { echo "update $type:$port input traffic failed!"; }
 done
 
 #OUTPUT
@@ -21,7 +21,7 @@ iptables -nvxLOUTPUT|grep -v Chain|grep -v pkts| while read record;do
     echo "new traffic:$traffic"
     echo "type:$type"
     echo "port:$port"
-    sqlite3 "$db" "update portConfig set outputTraffic = outputTraffic + $traffic where type=\"$type\" and port=$port;" || { echo "update $type:$port" output traffic failed! ;}
+    sqlite3 "$db" "update portConfig set outputTraffic = outputTraffic + $traffic where type=\"$type\" and port=$port;" || { echo "update $type:$port output traffic failed!"; }
 done
 
 /sbin/iptables -P INPUT ACCEPT
